name: Download and Upload Artifact
on: 
   workflow_dispatch:
     inputs:
       download_link:
         description: '请输入下载地址'
         required: true
       file_name:
         description: '请输入文件名字'
         required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: User Input
      id: input
      run: |
        echo "::set-output name=download_link::${{ github.event.inputs.download_link }}"
        echo "::set-output name=file_name::${{ github.event.inputs.file_name }}"

    - name: Download software
      run: |
        wget -O ${{ steps.config.outputs.file_name }} ${{ steps.config.outputs.download_link }

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.input.outputs.file_name }}
        path: ${{ steps.input.outputs.file_name }}
        retention-days: 3
