name: Download and Upload Artifact
on: 
   workflow_dispatch:
     inputs:
       download_link:
         description: '请输入下载地址'
         required: true
       file_name:
         description: '请输入文件名字'
         required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download software
      run: |
        wget -O ${{ github.event.inputs.file_name }} ${{ github.event.inputs.download_link }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.input.outputs.file_name }}
        path: ${{ steps.input.outputs.file_name }}
        retention-days: 3
